SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '입니다' AS "학과별 정원"
FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_SSN LIKE '_______2%' AND DEPARTMENT_NO = '001' AND ABSENCE_YN = 'Y';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO in ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY DESC;

SELECT DEPARTMENT_NAME ,CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND ENTRANCE_DATE LIKE '02%' AND STUDENT_ADDRESS LIKE '%전주%';