--1.
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN ='N'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE 
   STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%'
   AND STUDENT_NO LIKE '9%';

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

--5.
SELECT STUDENT_NO, TO_CHAR(POINT,'9.99') POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--6.
SELECT STUDENT_NO , STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR 
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR 
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = P.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--10.
SELECT STUDENT_NO "학번", STUDENT_NAME "학생 이름", "POINT" "전체 평점"
FROM (SELECT STUDENT_NO, ROUND(AVG(POINT),1) POINT FROM TB_GRADE GROUP BY STUDENT_NO) 
JOIN TB_STUDENT S USING (STUDENT_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
ORDER BY POINT DESC;

--11.
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE 
    S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
    AND STUDENT_NO = 'A313047';
    
--12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--14.
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';

--15.
SELECT S.STUDENT_NO "학번", S.STUDENT_NAME "이름", D.DEPARTMENT_NAME "학과 이름", G.POINT "평점"
FROM TB_STUDENT S, TB_DEPARTMENT D, (SELECT STUDENT_NO, AVG(POINT) POINT FROM TB_GRADE GROUP BY STUDENT_NO) G
WHERE 
    S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND S.STUDENT_NO = G.STUDENT_NO
    AND ABSENCE_YN = 'N'
    AND POINT >= 4;
    
--16.
SELECT CLASS_NO, CLASS_NAME, "AVG(POINT)"
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN (SELECT CLASS_NO , TRUNC(AVG(POINT),8)"AVG(POINT)" FROM TB_GRADE GROUP BY CLASS_NO) USING (CLASS_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%';

--17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

--18.
SELECT STUDENT_NO, STUDENT_NAME
FROM (
    SELECT STUDENT_NO, STUDENT_NAME, S
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN (SELECT STUDENT_NO, AVG(POINT) S FROM TB_GRADE GROUP BY STUDENT_NO) USING (STUDENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과'
    ORDER BY S DESC
)
WHERE ROWNUM < 2;

--19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) "전공 평점"
FROM (SELECT DISTINCT DEPARTMENT_NAME, DEPARTMENT_NO
      FROM TB_DEPARTMENT
      JOIN TB_CLASS USING(DEPARTMENT_NO)
      WHERE CLASS_TYPE LIKE '전공%' 
      AND CATEGORY = (SELECT CATEGORY 
                      FROM TB_DEPARTMENT 
                      WHERE DEPARTMENT_NAME = '환경조경학과'))
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (CLASS_NO)
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME;