--  1.
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO 번호;

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NAME TO 유형이름;
INSERT INTO TB_CLASS_TYPE
(
    SELECT '01' AS 번호 ,'전공필수' AS 유형이름 FROM DUAL
    UNION
    SELECT '02' AS 번호 ,'전공선택' AS 유형이름 FROM DUAL
    UNION
    SELECT '03' AS 번호 ,'교양필수' AS 유형이름 FROM DUAL
    UNION
    SELECT '04' AS 번호 ,'교양선택' AS 유형이름 FROM DUAL
    UNION
    SELECT '05' AS 번호 ,'논문지도' AS 유형이름 FROM DUAL
);

--  2.
CREATE TABLE TB_학생일반정보
AS (SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM TB_STUDENT);
    
--  3.
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,0,6),'RRMMDD'),'RRRR') AS 출생년도, PROFESSOR_NAME 교수이름
    FROM TB_STUDENT
    JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO);
    
--  4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY + CAPACITY * 0.1);

--  5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042' AND STUDENT_NAME = '박건우';

--  6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN,0,6);

--  7.
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501' AND CLASS_NO = (SELECT CLASS_NO
                                        FROM TB_CLASS
                                        WHERE CLASS_NAME = '피부생리학');

--  8.
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');