DROP TABLE SURVEY;
DROP TABLE CHOICE_ANS;
DROP TABLE CHOICE_OPTION;
DROP TABLE WRITE_ANS;
DROP TABLE ATTAND_CHECK;
DROP TABLE LUNCH;
DROP TABLE SCHEDULE;
DROP TABLE NOTICE;
DROP TABLE TIME_TABLE_ITEM;
DROP TABLE TIME_TABLE;
DROP TABLE BOOKMARK;
DROP TABLE REPLY;
DROP TABLE CHOICE_QUES;
DROP TABLE WRITE_QUES;
DROP TABLE ATTACHMENT;
DROP TABLE BOARD;
DROP TABLE CLASS_MEMBER;
DROP TABLE CLASS;
DROP TABLE MEMBER;
DROP TABLE QUESTION;

CREATE TABLE SURVEY (
	SURVEY_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(60)	NOT NULL,
	COUNT	NUMBER	NULL,
	FIRST_DATE	DATE	NULL,
	LAST_DATE	DATE	NULL,
	STATUS	VARCHAR2(1) DEFAULT 'Y'	NOT NULL,
	REF_CNO	NUMBER	NOT NULL
);

COMMENT ON TABLE SURVEY IS '설문';
COMMENT ON COLUMN SURVEY.SURVEY_NO IS '설문조사번호';
COMMENT ON COLUMN SURVEY.TITLE IS '제목';
COMMENT ON COLUMN SURVEY.COUNT IS '응답 인원수';
COMMENT ON COLUMN SURVEY.FIRST_DATE IS '시작일';
COMMENT ON COLUMN SURVEY.LAST_DATE IS '종료일';
COMMENT ON COLUMN SURVEY.STATUS IS '종료여부("Y"/"N")';
COMMENT ON COLUMN SURVEY.REF_CNO IS '클래스번호';

CREATE TABLE QUESTION (
	QUES_NO 	NUMBER	NOT NULL,
    REF_SNO 	NUMBER	NOT NULL,
	TYPE	NUMBER	DEFAULT 1 NOT NULL 
);

COMMENT ON TABLE QUESTION IS '질문';
COMMENT ON COLUMN QUESTION.QUES_NO IS '질문번호';
COMMENT ON COLUMN QUESTION.REF_SNO IS '설문조사번호';
COMMENT ON COLUMN QUESTION.TYPE IS '질문타입(1:객/2:주)';

CREATE TABLE CHOICE_QUES (
	QUES_NO	 NUMBER	NOT NULL,
	QUES_TITLE 	VARCHAR2(60)	NOT NULL,
	QUES_CONTENT	VARCHAR2(500)	NULL
);

COMMENT ON TABLE CHOICE_QUES IS '객관식질문';
COMMENT ON COLUMN CHOICE_QUES.QUES_NO IS '질문번호';
COMMENT ON COLUMN CHOICE_QUES.QUES_TITLE IS '질문제목';
COMMENT ON COLUMN CHOICE_QUES.QUES_CONTENT IS '질문내용';

CREATE TABLE WRITE_QUES (
	QUES_NO	 NUMBER	NOT NULL,
	QUES_TITLE	VARCHAR2(60)	NOT NULL,
	QUES_CONTENT	VARCHAR2(500)	NULL
);

COMMENT ON TABLE WRITE_QUES IS '주관식질문';
COMMENT ON COLUMN WRITE_QUES.QUES_NO IS '질문번호';
COMMENT ON COLUMN WRITE_QUES.QUES_TITLE IS '질문제목';
COMMENT ON COLUMN WRITE_QUES.QUES_CONTENT IS '질문내용';

CREATE TABLE CHOICE_ANS (
	ITEM_NO  NUMBER	NOT NULL,
	COUNT	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON TABLE CHOICE_ANS IS '주관식답안';
COMMENT ON COLUMN CHOICE_ANS.ITEM_NO IS '항목번호';
COMMENT ON COLUMN CHOICE_ANS.COUNT IS '응답자 수';

CREATE TABLE CHOICE_OPTION (
    ITEM_NO 	NUMBER	NOT NULL,
	REF_QNO     NUMBER	NOT NULL,
	ITEM_CONTENT	VARCHAR2(100)	NOT NULL
);

COMMENT ON TABLE CHOICE_OPTION IS '객관식항목';
COMMENT ON COLUMN CHOICE_OPTION.ITEM_NO IS '항목번호';
COMMENT ON COLUMN CHOICE_OPTION.REF_QNO IS '질문번호';
COMMENT ON COLUMN CHOICE_OPTION.ITEM_CONTENT IS '항목내용';

CREATE TABLE WRITE_ANS (
	QUES_NO 	NUMBER	NOT NULL,
	SUBMIT_DATE	DATE	DEFAULT SYSDATE NOT NULL,
	ANSWER  	VARCHAR2(1000)	NULL,
	REF_UNO 	NUMBER	NOT NULL
);

COMMENT ON TABLE WRITE_ANS IS '객관식답안';
COMMENT ON COLUMN WRITE_ANS.QUES_NO IS '질문번호';
COMMENT ON COLUMN WRITE_ANS.SUBMIT_DATE IS '제출일시';
COMMENT ON COLUMN WRITE_ANS.ANSWER IS '답안 내용';
COMMENT ON COLUMN WRITE_ANS.REF_UNO IS '회원번호';

CREATE TABLE MEMBER (
	USER_NO	NUMBER	NOT NULL,
	USER_ID	VARCHAR2(30)	NOT NULL,
	USER_PWD	VARCHAR2(300)	NOT NULL,
	USER_NAME	VARCHAR2(30)	NOT NULL,
	PHONE	VARCHAR2(20)	NULL,
	ADDRESS	VARCHAR2(100)	NULL,
	ENROLL_DATE	DATE	DEFAULT SYSDATE 	NOT NULL,
	MODIFY_DATE	DATE	DEFAULT SYSDATE 	NOT NULL,
	STATUS	VARCHAR2(1)	DEFAULT 'Y' 	NOT NULL,
	CHILDREN_NAME	VARCHAR2(30)	NULL,
	USER_LEVEL	NUMBER	NOT NULL
);

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입날짜';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.CHILDREN_NAME IS '자녀이름';
COMMENT ON COLUMN MEMBER.USER_LEVEL IS '레벨(1:선,2:부,3:학)';

CREATE TABLE ATTACHMENT (
	FILE_NO	NUMBER	NOT NULL,
	REF_BNO	NUMBER	NOT NULL,
	ORIGIN_NAME	VARCHAR2(300)	NOT NULL,
	CHANGE_NAME	VARCHAR2(300)	NOT NULL,
	FILE_PATH	VARCHAR2(1000)	NOT NULL,
	UPLOAD_DATE	DATE	DEFAULT SYSDATE     NOT NULL,
	FILE_LEVEL	NUMBER	NULL,
	STATUS	VARCHAR2(1)	DEFAULT 'Y' 	NOT NULL
);

COMMENT ON TABLE ATTACHMENT IS '파일';
COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.REF_BNO IS '게시글번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.FILE_LEVEL IS '파일레벨(1:메인사진/2:사이드사진)';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태값(Y/N)';

CREATE TABLE BOARD (
	BOARD_NO	NUMBER	NOT NULL,
	BOARD_TYPE	NUMBER	NOT NULL,
	BOARD_TITLE	VARCHAR2(60)	NOT NULL,
	BOARD_CONTENT	VARCHAR2(3000)	NOT NULL,
	COUNT	NUMBER	NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	VARCHAR2(1) DEFAULT 'Y'     NOT NULL,
	SECRET	VARCHAR2(1)	DEFAULT 'N'     NOT NULL,
	LIKES	NUMBER	DEFAULT 0   NULL,
	REF_CNO 	NUMBER	NOT NULL
);

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시글타입(1~5)';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)삭제';
COMMENT ON COLUMN BOARD.SECRET IS '상태값(Y/N) 비밀(선생님만)';
COMMENT ON COLUMN BOARD.LIKES IS '좋아요수';
COMMENT ON COLUMN BOARD.REF_CNO IS '클래스번호';

CREATE TABLE CLASS (
	CLASS_NO	NUMBER	NOT NULL,
	CLASS_GRADE	NUMBER	NOT NULL,
	CLASS_CODE	NUMBER	NULL,
	CLASS_NAME	VARCHAR2(60)	DEFAULT '클래스 이름이 없습니다.'	NOT NULL,
	CLASS_TYPE_NAME	 VARCHAR2(60)	DEFAULT '학급 이름이 없습니다. 	NOT NULL'
);

COMMENT ON TABLE CLASS IS '클래스';
COMMENT ON COLUMN CLASS.CLASS_NO IS '클래스번호';
COMMENT ON COLUMN CLASS.CLASS_GRADE IS '학년';
COMMENT ON COLUMN CLASS.CLASS_CODE IS '초대코드';
COMMENT ON COLUMN CLASS.CLASS_NAME IS '클래스 이름';
COMMENT ON COLUMN CLASS.CLASS_TYPE_NAME IS '학교/학원 이름';

CREATE TABLE REPLY (
	REPLY_NO	NUMBER	NOT NULL,
	REF_BNO	 NUMBER	NOT NULL,
	REPLY_CONTENT	VARCHAR2(500)	NOT NULL,
	REPLY_WRITER	NUMBER	NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE     NOT NULL,
	STATUS	VARCHAR2(1)	DEFAULT 'Y'     NULL,
	REPLY_SECRET	VARCHAR2(1)	DEFAULT 'N'   NULL
);

COMMENT ON TABLE REPLY IS '댓글';
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REF_BNO IS '참조게시글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '작성자회원번호';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성일';
COMMENT ON COLUMN REPLY.STATUS IS '삭제여부(Y/N)';
COMMENT ON COLUMN REPLY.REPLY_SECRET IS '비밀댓글여부(Y/N)';

CREATE TABLE CLASS_MEMBER (
	CLASS_NO	NUMBER	NOT NULL,
	REF_UNO	NUMBER	NOT NULL,
	STUDENT_NO	NUMBER	NULL
);

COMMENT ON TABLE CLASS_MEMBER IS '클래스회원';
COMMENT ON COLUMN CLASS_MEMBER.CLASS_NO IS '클래스번호';
COMMENT ON COLUMN CLASS_MEMBER.REF_UNO IS '회원번호';
COMMENT ON COLUMN CLASS_MEMBER.STUDENT_NO IS '학생 반 번호';

CREATE TABLE ATTAND_CHECK (
	USER_NO	NUMBER	NOT NULL,
	A_STATUS	NUMBER	NULL,
	MONTH	DATE	NULL,
	DAY	DATE	NULL,
	REF_CNO	NUMBER	NOT NULL
);

COMMENT ON TABLE ATTAND_CHECK IS '출석체크';
COMMENT ON COLUMN ATTAND_CHECK.USER_NO IS '회원번호';
COMMENT ON COLUMN ATTAND_CHECK.A_STATUS IS '출석 상태(1:출석, 2:결석, 3:지각)';
COMMENT ON COLUMN ATTAND_CHECK.MONTH IS '월';
COMMENT ON COLUMN ATTAND_CHECK.DAY IS '일';
COMMENT ON COLUMN ATTAND_CHECK.REF_CNO IS '클래스번호';


CREATE TABLE LUNCH (
	LUNCH_NO	NUMBER	NOT NULL,
	YEAR	DATE	NOT NULL,
	MONTH	DATE	NOT NULL,
	DAY	DATE	NOT NULL,
	MENU	VARCHAR2(60)	NOT NULL,
	REF_CNO	NUMBER	NOT NULL
);

COMMENT ON TABLE LUNCH IS '급식표';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '급식번호';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '년';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '월';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '일';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '메뉴';
COMMENT ON COLUMN LUNCH.LUNCH_NO IS '클래스번호';

CREATE TABLE TIME_TABLE (
	TIME_TABLE_NO	NUMBER	NOT NULL,
	REF_CNO	NUMBER	NOT NULL
);

COMMENT ON TABLE TIME_TABLE IS '시간표';
COMMENT ON COLUMN TIME_TABLE.TIME_TABLE_NO IS '시간표번호';
COMMENT ON COLUMN TIME_TABLE.REF_CNO IS '클래스번호';

CREATE TABLE SCHEDULE (
	SCHEDULE_NO	NUMBER	NOT NULL,
	YEAR	DATE	NOT NULL,
	MONTH	DATE	NOT NULL,
	DAY	DATE	NOT NULL,
	CONTENT	 VARCHAR2(300)	NOT NULL,
	REF_CNO	 NUMBER	NOT NULL
);

COMMENT ON TABLE SCHEDULE IS '학급일정표';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '일정번호';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '년';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '월';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '일';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '내용';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NO IS '클래스번호';

CREATE TABLE NOTICE (
	REF_BNO	NUMBER	NOT NULL,
	READ_STATUS	VARCHAR2(1)	DEFAULT 'N'   NOT NULL,
	REF_UNO	NUMBER	NOT NULL
);

COMMENT ON TABLE NOTICE IS '알림장';
COMMENT ON COLUMN NOTICE.REF_BNO IS '게시글번호';
COMMENT ON COLUMN NOTICE.READ_STATUS IS '읽음상태(읽음:Y/N)';
COMMENT ON COLUMN NOTICE.REF_UNO IS '회원번호';

CREATE TABLE TIME_TABLE_ITEM (
	TIME_TABLE_NO	NUMBER	NOT NULL,
	ITEM_NO	NUMBER	NULL,
	TITLE	VARCHAR2(60)	NULL,
	CONTENT	VARCHAR2(60)	NULL,
	TIME	VARCHAR2(100)	NULL
);

COMMENT ON TABLE TIME_TABLE_ITEM IS '시간표항목';
COMMENT ON COLUMN TIME_TABLE_ITEM.TIME_TABLE_NO IS '시간표번호';
COMMENT ON COLUMN TIME_TABLE_ITEM.ITEM_NO IS '항목번호';
COMMENT ON COLUMN TIME_TABLE_ITEM.TITLE IS '제목';
COMMENT ON COLUMN TIME_TABLE_ITEM.CONTENT IS '내용';
COMMENT ON COLUMN TIME_TABLE_ITEM.TIME IS '시간';

CREATE TABLE BOOKMARK (
	USER_NO	NUMBER	NOT NULL,
	BOARD_NO	NUMBER	NOT NULL,
	BOARD_TYPE	NUMBER	NOT NULL
);

COMMENT ON TABLE BOOKMARK IS '스크랩';
COMMENT ON COLUMN BOOKMARK.USER_NO IS '회원번호';
COMMENT ON COLUMN BOOKMARK.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOOKMARK.BOARD_TYPE IS '게시글타입(1~5)';

ALTER TABLE SURVEY ADD CONSTRAINT PK_SURVEY PRIMARY KEY (
	SURVEY_NO
);

ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY (
	QUES_NO
);

ALTER TABLE CHOICE_QUES ADD CONSTRAINT PK_CHOICE_QUES PRIMARY KEY (
	QUES_NO
);

ALTER TABLE WRITE_QUES ADD CONSTRAINT PK_WRITE_QUES PRIMARY KEY (
	QUES_NO
);

ALTER TABLE CHOICE_ANS ADD CONSTRAINT PK_CHOICE_ANS PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE CHOICE_OPTION ADD CONSTRAINT PK_CHOICE_OPTION PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE WRITE_ANS ADD CONSTRAINT PK_WRITE_ANS PRIMARY KEY (
	QUES_NO
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	USER_NO
);

ALTER TABLE ATTACHMENT ADD CONSTRAINT PK_ATTACHMENT PRIMARY KEY (
	FILE_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE CLASS ADD CONSTRAINT PK_CLASS PRIMARY KEY (
	CLASS_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE CLASS_MEMBER ADD CONSTRAINT PK_CLASS_MEMBER PRIMARY KEY (
	CLASS_NO
);

ALTER TABLE ATTAND_CHECK ADD CONSTRAINT PK_ATTAND_CHECK PRIMARY KEY (
	USER_NO
);

ALTER TABLE LUNCH ADD CONSTRAINT PK_LUNCH PRIMARY KEY (
	LUNCH_NO
);

ALTER TABLE TIME_TABLE ADD CONSTRAINT PK_TIME_TABLE PRIMARY KEY (
	TIME_TABLE_NO
);

ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (
	SCHEDULE_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	REF_BNO
);

ALTER TABLE TIME_TABLE_ITEM ADD CONSTRAINT PK_TIME_TABLE_ITEM PRIMARY KEY (
	TIME_TABLE_NO
);

ALTER TABLE BOOKMARK ADD CONSTRAINT PK_BOOKMARK PRIMARY KEY (
	USER_NO
);

ALTER TABLE CHOICE_QUES ADD CONSTRAINT FK_CHOICE_QUES_1 FOREIGN KEY (
	QUES_NO
)
REFERENCES QUESTION (
	QUES_NO
);

ALTER TABLE WRITE_QUES ADD CONSTRAINT FK_WRITE_QUES_1 FOREIGN KEY (
	QUES_NO
)
REFERENCES QUESTION (
	QUES_NO
);

ALTER TABLE CHOICE_ANS ADD CONSTRAINT FK_CHOICE_ANS_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES CHOICE_OPTION (
	ITEM_NO
);

ALTER TABLE WRITE_ANS ADD CONSTRAINT FK_WRITE_ANS_1 FOREIGN KEY (
	QUES_NO
)
REFERENCES WRITE_QUES (
	QUES_NO
);

ALTER TABLE CLASS_MEMBER ADD CONSTRAINT FK_CLASS_MEMBER_1 FOREIGN KEY (
	CLASS_NO
)
REFERENCES CLASS (
	CLASS_NO
);

ALTER TABLE ATTAND_CHECK ADD CONSTRAINT FK_ATTAND_CHECK_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_1 FOREIGN KEY (
	REF_BNO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE TIME_TABLE_ITEM ADD CONSTRAINT FK_TIME_TABLE_ITEM_1 FOREIGN KEY (
	TIME_TABLE_NO
)
REFERENCES TIME_TABLE (
	TIME_TABLE_NO
);

ALTER TABLE BOOKMARK ADD CONSTRAINT FK_MEMBER_TO_BOOKMARK_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

